In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('Books.csv')
ratings = pd.read_csv('Ratings.csv')
users = pd.read_csv('Users.csv')

C:\Users\gehan\AppData\Local\Temp\ipykernel_11560\378180666.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [3]:
books.describe()
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

## Popularity based recommendation system

In [5]:
ratings_with_name=ratings.merge(books,on='ISBN')

In [6]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [7]:
avg_rating_df=ratings_with_name.groupby('Book-Title').mean(numeric_only=True)['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [8]:
popular_df= num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [9]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_ratings',ascending=False).head(50)

In [10]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','num_ratings','avg_ratings','Image-URL-M']]
popular_df

,Book-Title,Book-Author,num_ratings,avg_ratings,Image-URL-M
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,428,5.852804,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,387,5.824289,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,278,5.737410,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,347,5.501441,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,556,5.183453,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,281,5.007117,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,368,4.948370,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,575,4.895652,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,260,4.880769,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,Harper Lee,510,4.700000,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,Dan Brown,898,4.642539,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,Mitch Albom,430,4.551163,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,J.D. Salinger,449,4.545657,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,Alice Sebold,1295,4.468726,http://images.amazon.com/images/P/0316666343.0...
63,1984,George Orwell,284,4.454225,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,Barbara Kingsolver,253,4.450593,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,Neil Gaiman,265,4.449057,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,Sue Monk Kidd,774,4.447028,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,283,4.356890,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,493,4.354970,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),Anita Diamant,723,4.334716,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,268,4.328358,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,335,4.289552,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,Jon Krakauer,252,4.273810,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,Ray Bradbury,409,4.264059,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,Tracy Chevalier,526,4.218631,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,DIANA GABALDON,283,4.173145,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,585,4.105983,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,275,4.098182,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,Yann Martel,664,4.088855,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,Barbara Kingsolver,389,4.087404,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,265,4.086792,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,Frank McCourt,279,4.075269,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,Jennifer Weiner,490,4.055102,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,321,4.037383,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,Neil Gaiman,302,4.006623,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,JOHN GRISHAM,322,4.006211,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,318,4.003145,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,336,4.000000,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,Alice Walker,314,3.964968,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,Thomas Harris,256,3.960938,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,Nick Hornby,262,3.900763,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,278,3.888489,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,266,3.875940,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,269,3.825279,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,James Patterson,457,3.820569,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,William Gerald Golding,259,3.818533,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,John Irving,413,3.796610,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,301,3.777409,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,356,3.772472,http://images.amazon.com/images/P/0316284955.0...

## Collaborative Filtering Based Recommender System

In [11]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
literate_users=x[x].index

In [12]:
filtered_rating= ratings_with_name[ratings_with_name['User-ID'].isin(literate_users)]

In [13]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=y[y].index

In [14]:
final_ratings=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [15]:
pivot_table=final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')
pivot_table.fillna(0,inplace=True)

In [16]:
pivot_table

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [17]:
from sklearn.metrics.pairwise import cosine_similarity as cs

In [18]:
similarity_score=cs(pivot_table)

In [19]:
similarity_score.shape

(706, 706)

In [20]:
def recommend(book_name):
    #fetch index
    index= np.where(pivot_table.index==book_name)[0][0]
    similar_items= sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1],reverse=True)[1:6]
    
    data=[]
    for i in similar_items:
        item=[]
        temp_df=books[books['Book-Title']== pivot_table.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-L'].values))
        
        data.append(item)
    return data

In [22]:
recommend('Zoya')

[['Fine Things',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0440200563.01.MZZZZZZZ.jpg'],
 ['Secrets',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0440176484.01.MZZZZZZZ.jpg'],
 ['Kaleidoscope',
  'June Stepansky',
  'http://images.amazon.com/images/P/0884092097.01.MZZZZZZZ.jpg'],
 ['Exclusive',
  'Sandra Brown',
  'http://images.amazon.com/images/P/0446604232.01.MZZZZZZZ.jpg'],
 ['Five Days in Paris',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0440222842.01.MZZZZZZZ.jpg']]

In [25]:
import pickle

In [33]:
pickle.dump(famous_books,open('fam_books.pkl', 'wb'))

In [32]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [34]:
pickle.dump(pivot_table,open('pivot_table.pkl', 'wb'))
pickle.dump(books,open('books.pkl', 'wb'))
pickle.dump(similarity_score,open('similarity_score.pkl', 'wb'))

In [35]:
pickle.dump(popular_df,open('popular_df.pkl', 'wb'))

In [50]:
popular_df['Image-URL-M'][28]

'http://images.amazon.com/images/P/0345339711.01.MZZZZZZZ.jpg'